export const PRODUCTS = [
  {
    id: 1,
    name: "Premium Wireless Headphones",
    category: "Audio",
    price: "$199",
    rating: 4.8,
    reviews: 1250,
    image: "/premium-wireless-headphones.png",
    amazonUrl: "https://amazon.com/s?k=premium+wireless+headphones",
    description:
      "Experience crystal-clear audio with our premium wireless headphones. Featuring active noise cancellation, 30-hour battery life, and superior comfort.",
    features: [
      "Active Noise Cancellation (ANC)",
      "30-hour battery life",
      "Bluetooth 5.3 connectivity",
      "Premium memory foam ear cushions",
      "Built-in microphone for calls",
      "Foldable design for portability",
    ],
    specs: {
      "Driver Size": "40mm",
      "Frequency Response": "20Hz - 20kHz",
      Impedance: "32 Ohms",
      Connectivity: "Bluetooth 5.3",
      "Battery Life": "30 hours",
      "Charging Time": "2 hours",
    },
    pros: [
      "Excellent sound quality",
      "Long battery life",
      "Comfortable for extended wear",
      "Effective noise cancellation",
    ],
    cons: ["Relatively expensive", "May feel heavy for some users"],
  },
  {
    id: 2,
    name: "Minimalist Smart Watch",
    category: "Wearables",
    price: "$299",
    rating: 4.7,
    reviews: 890,
    image: "/minimalist-smart-watch.jpg",
    amazonUrl: "https://amazon.com/s?k=minimalist+smart+watch",
    description:
      "A sophisticated timepiece that seamlessly blends classic design with cutting-edge technology. Track your health and stay connected in style.",
    features: [
      "AMOLED display",
      "Heart rate monitoring",
      "Sleep tracking",
      "7-day battery life",
      "Water resistant up to 50m",
      "Multiple watch faces",
    ],
    specs: {
      Display: "1.4-inch AMOLED",
      Resolution: "454 x 454 pixels",
      "Water Resistance": "5ATM (50m)",
      Battery: "430mAh",
      "Battery Life": "7 days",
      Weight: "32g",
    },
    pros: [
      "Beautiful minimalist design",
      "Excellent AMOLED display",
      "Good battery life",
      "Reliable health tracking",
    ],
    cons: ["Limited app ecosystem", "High price point"],
  },
  {
    id: 3,
    name: "Ergonomic Mechanical Keyboard",
    category: "Computing",
    price: "$149",
    rating: 4.9,
    reviews: 2100,
    image: "/mechanical-keyboard.png",
    amazonUrl: "https://amazon.com/s?k=ergonomic+mechanical+keyboard",
    description:
      "Professional-grade mechanical keyboard with ergonomic design for reduced strain during extended typing sessions. Perfect for programmers and content creators.",
    features: [
      "Mechanical switches",
      "Ergonomic split design",
      "RGB backlight",
      "Programmable keys",
      "USB-C connection",
      "Aluminum frame",
    ],
    specs: {
      "Switch Type": "Mechanical (Cherry MX equivalent)",
      Layout: "Split Ergonomic",
      Connection: "USB-C Wired",
      Backlight: "RGB per-key",
      Material: "Aluminum + ABS",
      Weight: "2.4kg",
    },
    pros: [
      "Excellent typing experience",
      "Ergonomic design reduces strain",
      "High-quality build",
      "Highly rated by users",
    ],
    cons: ["Requires learning curve", "Not ideal for travel"],
  },
  {
    id: 4,
    name: "Premium Portable Speaker",
    category: "Audio",
    price: "$249",
    rating: 4.6,
    reviews: 756,
    image: "/portable-speaker.png",
    amazonUrl: "https://amazon.com/s?k=premium+portable+speaker",
    description:
      "Compact yet powerful portable speaker with 360-degree sound. Enjoy exceptional audio quality anywhere with all-day battery life.",
    features: [
      "360-degree sound",
      "20-hour battery life",
      "Water resistant (IPX7)",
      "Bluetooth 5.0",
      "Built-in microphone",
      "Compact design",
    ],
    specs: {
      Drivers: "Dual 10W drivers",
      "Frequency Response": "50Hz - 20kHz",
      Battery: "5000mAh",
      "Battery Life": "20 hours",
      "Water Resistance": "IPX7",
      Size: "7.5 x 7.5 x 8.2 inches",
    },
    pros: [
      "Great sound for the size",
      "Long battery life",
      "Durable and water resistant",
      "Easy to carry",
    ],
    cons: ["Not as powerful as larger speakers", "Limited bass response"],
  },
];
